### ISSUE TITLE
When we click 'update draft' button, the time displayed should show the time of the latest update.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#161] opened 2023-01-09 10:33 UTC

**Comment by tusharravindran** [comment] 2023-01-09 16:26
Issue 161 Resolved in Branch Issue/#161 #172

**Comment by mithun30052001** [comment] 2023-01-11 08:28
The issue is fixed and code is upto date in master

**Closed** 2023-01-16 06:51 UTC
Labels: bug
